# jangan lupa untuk uncomment ls command dalam bashrc 
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# navi
alias h='cd ~ && clear'
alias ..='cd ..'
alias cod='cd ~/cod'
alias reload='source ~/.bashrc && echo "~/.bashrc reloaded!"'

# apps
alias t='flatpak run org.telegram.desktop'
alias obsi='nohup ~/cod/apps/Obsidian-1.12.7.AppImage --no-sandbox > /dev/null 2>&1 &'
alias bat='batcat'
alias a='cmus'

# mv semua lagu dalam tele desktop dir ke dalam music folder
alias areload='find "$HOME/dow/tele" -maxdepth 1 -type f \( -iname "*.mp3" -o -iname "*.flac" \) -exec mv -v {} "$HOME/a/" \;'

alias rm='rm -i'
alias rmf='/bin/rm -rf'
alias shut='sudo shutdown now'
alias zz='systemctl suspend'
alias restart='echo "Reboot? (y/n)" && read ans && [ "$ans" == "y" ] && sudo reboot'
alias fa='vim $(fzf -m --preview="bat --color=always {}")'
alias ga='git add .'
alias gi='git init'
alias gc='git commit'
alias gcu='git commit -m 'Update''
alias gp='git push origin main'
alias op='batcat ~/cod/Vexo/All\ Creda/whoami.md'
alias voo='vim ~/cod/Vexo/Polymath\ Mind.Log/du.md'
alias oo='batcat ~/cod/Vexo/Polymath\ Mind.Log/du.md'
alias vim='nvim'
