# === NAVIGATION & SYSTEM ===
alias h='cd ~'
alias ..='cd ..'
alias cod='cd ~/cod'
alias reload='source ~/.bashrc && echo "~/.bashrc reloaded!"'
alias c='clear'
alias la='ls -la'

# === APPS (GUNA FULL PATH) ===
alias t='flatpak run org.telegram.desktop'
alias obsi='~/cod/apps/Obsidian-1.12.7.AppImage --no-sandbox'

# === TOOLS ===
alias bat='batcat'

# === AUDIO & AUTOMATION ===
alias a='cmus'
# areload dibaiki supaya guna Full Path untuk mv
alias areload='find "$HOME/dow/tele" -maxdepth 1 -type f \( -iname "*.mp3" -o -iname "*.flac" \) -exec mv -v {} "$HOME/a/" \;'

# === SAFETY & POWER  ===
alias rm='rm -i'
alias rmf='/bin/rm -rf'
alias shut='sudo shutdown now'
alias zz='systemctl suspend'
alias restart='echo "Reboot? (y/n)" && read ans && [ "$ans" == "y" ] && sudo reboot'
alias fa='vim $(fzf -m --preview="bat --color=always {}")'
alias ga='git add .'
alias gi='git init'
alias gc='git commit'
alias gp='git push origin main'
alias op='batcat ~/cod/Vexo/FaezOS/All\ Creda/whoami.md'
alias oo='batcat ~/cod/Vexo/FaezOS/Polymath\ Mind.Log/Polymath\ Mind.Log.md'

