alias h='cd ~'
alias ..='cd ..'
alias codesa='cd ~/Documents/Codesa'
alias c='clear'
alias reload='source ~/.bashrc && echo "~/.bashrc reloaded!"'

# === APPS (GUNA FULL PATH) ===
alias t='flatpak run org.telegram.desktop'
alias putty='GDK_BACKEND=x11 putty'
alias z='(flatpak run app.zen_browser.zen &>/dev/null & disown)'

# Obsidian
alias obsidian='/home/f8un/Obsidian-1.11.7.AppImage --no-sandbox'

# === TOOLS ===
alias bat='batcat'

# === AUDIO & AUTOMATION ===
alias a='cmus'
# areload dibaiki supaya guna Full Path untuk mv
alias areload='find "$HOME/Downloads/Telegram Desktop" -maxdepth 1 -type f \( -iname "*.mp3" -o -iname "*.flac" \) -exec mv -v {} "$HOME/Music/" \;'

# === SAFETY & POWER  ===
alias rm='rm -i'
alias rmf='/bin/rm -rf'
alias shut='sudo shutdown now'
alias zz='systemctl suspend'
alias restart='echo "Reboot? (y/n)" && read ans && [ "$ans" == "y" ] && sudo reboot'
alias fa='vim $(fzf -m --preview="bat --color=always {}")'
