# Path : Dalam settings CMUS press '7' 67 btw

# Masukkan dir lagu dalam CMUS 
 :add /DATA/Media/Music (MUSIC DIR)
 :colorscheme gruvbox

# Foward & rewind lagu
:unbind common m 
:bind common m seek +5
:unbind common n
:bind common n seek -5

# quit without tanya confirmation nak quit 
:bind -f common q quit

# Play & pause lagu
:unbind common space 
:bind common space player-pause

# Previous & next lagu
:unbind commmon S
:bind common S player-prev-album
:unbind common D
:bind common D player-next

# Unbind unnecessary keybinds
:unbind common E
:unbind common F
:unbind common L
:unbind common N
:unbind common b
:unbind common v
:unbind common x

# Volume Up & Down
:unbind common -
:bind common - vol -5%
:unbind common =  # Kalau ada keybind 
:bind common = vol +5%

# buang .tracknumber dekat library
:set format_playlist= %-21%a  %t%= %d

# Title lagu sahaja yang display dekat nama tab without nama albumartist
:set format_title=  %l

 confirm_run                   true
 continue                      true
 format_current                 %a - %l  %=ALBUM: %t
 format_playlist                %-21%a %t%= %d
 format_playlist_va             %-21%A %t (%a)%=  %d
 format_trackwin               %t%= %y %d
 format_trackwin_album          %l %= %{albumduration}
 format_trackwin_va             %t (%a)%= %d
 format_treewin                  %l
 format_treewin_artist         %a
 lib_sort                      title albumartist album 
 mouse                         false
 mpris                         true
 output_plugin                 pulse
 passwd
 pause_on_output_change        false
 pl_sort
 play_library                  true
 play_sorted                   false
 repeat                        true
 repeat_current                false
 replaygain                    disabled
 replaygain_limit              true
 replaygain_preamp             0.000000
 resume                        true
 rewind_offset                 5
 scroll_offset                 2
 set_term_title                false
 show_all_tracks               true
 show_current_bitrate          false
 show_hidden                   false
 show_playback_position        true
 show_remaining_time           false
 shuffle                       albums
 skip_track_info               false
 smart_artist_sort             true
 softvol                       false
 softvol_state                 0 0
 start_view                    tree
 status_display_program
 stop_after_queue              false
 time_show_leading_zero        true
 tree_width_max                0
