# Path : .vimrc

set number
set relativenumber
set hlsearch
set incsearch
set tabstop=4
set shiftwidth=4
set expandtab
syntax on
set list


" Gunakan simbol vertical bar untuk tab"
set listchars=tab:\|\ ,trail:-,nbsp:+

" Paste ni juga untuk bagi warna garisan tu tak terlalu terang (lowkey)"
highlight SpecialKey ctermfg=darkgray guifg=gray

" Aktifkan syntax highlighting"
syntax on

" Set colorscheme (contoh: desert)"
colorscheme default

"Vim kenal jenis file"
filetype plugin on

"Aktifkan HTML"
set omnifunc=htmlcomplete#CompleteTags
