# Path : .vimrc

set number
set hlsearch
set incsearch
set tabstop=4
set shiftwidth=4
set expandtab
syntax on


" Aktifkan syntax highlighting"
syntax on

" Set colorscheme (contoh: desert)"
colorscheme default

"Vim kenal jenis file"
filetype plugin on

"Aktifkan HTML"
set omnifunc=htmlcomplete#CompleteTags
